### ISSUE TITLE
Team3 Question 9 Feedback

### ISSUE THREAD

**Issue by hodevin** [Allegheny-Computer-Science-203-S2020/cs203-S2020-management#12]
https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-management/commit/bcf24777ecaaf5ef90e223b81c92d0622b1e42d5

Hi all, @liux2 and I have added our answers into a paragraph. We summarized points from every assignees' initial brainstorming ideas. Please go to the [team3-question9](https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-management/tree/team3-question9) branch and view the `management.md` file to see what we have added.

Please comment with any suggested changes or additions you may have.

**Comment by santacruzm** [comment]
**Great Work.** 

I agree with you on doing research ahead of time in order to determine whether the project is feasible or not. I do notice some repetition with the following sentence considering you hint at this idea in the first sentence. If so I would suggest rephrasing or perhaps deleting the sentence. 

"However, be aware that the team should do research at the beginning of the project to decide if a feature is feasible."

**Comment by Jordan-A** [comment]
I like that you have formatted your work in a paragraph instead of bullet points. I would also rephrase some sentences that @santacruzm  mentioned.

Good work!

**Comment by liux2** [comment]
The first part was about under the situation that if a feature is not implementable, what the solution could be. It is at the stage after the team decides the features. The "However" part is a reminder to pick feasible features. It is at the pre-implementation stage.

**Comment by liux2** [comment]
Revised the two sentences to make them less vague.
https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-management/commit/5673008ac40f9fc1420bb49c9c016717b35c9ca4

**Comment by lussierc** [comment]
I don't see any issues with this branch after the requested changes were implemented. Thanks for adding my thoughts from last week's discussion about how it is better to completely finish some work than partially finish all of it when it comes to implementing features.
