### ISSUE TITLE
Use of colons

### ISSUE THREAD

**Issue by cklima616** [Allegheny-Computer-Science-203-S2020/cs203-S2020-management#17]
Hello, I recognize that this is a problem because we did not account for this format in the provided guidelines, but we should decide whether or not to use colons after bullet point titles. I just noticed it isn't consistent in our master branch.

**Comment by schultzh** [comment]
I think it looks cleaner without colons. Thoughts from anyone else?

**Comment by cklima616** [comment]
@schultzh I agree. I can make an announcement in Slack?
