### ISSUE TITLE
Pull Requests do not require 4 Reviews for merging

### ISSUE THREAD

**Issue by koscinskic** [Allegheny-Computer-Science-203-S2020/cs203-S2020-management#4]
Currently, the security and policy settings on this repository are not configured to prevent merging without having the professor and teaching assistants review the PR. Could the administrators of this repository either configure this setting for us or add "stephensonc" and "koscinskic" as contributors?

**Comment by enpuyou** [comment]
Hi @koscinskic! Thanks for raising this issue. 

- I have updated the branch protection rules for this repository and it now requires at least 4 approvals to be merged. As @gkapfham pointed out you should also be asking the members of your course to review the PRs and provide detailed and useful feedback, meaning the reviewers being assigned could be and should be more than 4. What do you think? 

- I assume you meant administrator here by "contributors". I'm definitely open to having you or @stephensonc becoming the administrator, as that will enable students to manage the repository and be responsible for the code they are writing, but I feel TLs don't really have the say on who should be granted the admin access and who shouldn't. Thus, I believe it will be a great idea for you to announce and discuss this in class and have everyone participated to select "product managers" who will have the admin access.
