### ISSUE TITLE
Team3 Question 8 Feedback

### ISSUE THREAD

**Issue by lussierc** [Allegheny-Computer-Science-203-S2020/cs203-S2020-management#6]
Hi all, we have continued our work on Question 8. Please go to the [team3-question8 branch](https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-management/tree/team3-question8) and view the `management.md` file to see what we have added.

Please comment with any suggested changes or additions you may have.

**Comment by Jordan-A** [comment]
I like what you have so far, especially the second bullet point. But according to the [markdown guidelines](https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-markdown/blob/master/ProjectManagementFormat.md) for the second lab they specify that the response has to be in a paragraph. Also I would remove the parenthesis. 

Other than that I like what you have!

**Comment by lussierc** [comment]
> I like what you have so far, especially the second bullet point. But according to the [markdown guidelines](https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-markdown/blob/master/ProjectManagementFormat.md) for the second lab they specify that the response has to be in a paragraph. Also I would remove the parenthesis.
> 
> Other than that I like what you have!

Good call on the paragraphs, I will implement these changes at some point in the near future, @Jordan-A.

**Comment by liux2** [comment]
When you implement the paragraphs, could you add bullet point titles for each paragraph?

**Comment by liux2** [comment]
Nevermind, the majority of the people are doing a one-paragraph answer. I made the comment because the professor mentioned 3-5 points per answer. Then we decide to use bullet points. After someone suggested using "paragraph" instead of bullet points, now we have a 3-5 sentence paragraph requirement.

**Comment by santacruzm** [comment]
**Great Work** 
After reviewing the previous suggestions, you have effectively discussed well-thought-out points here. Remember to implement the paragraph style which Jordan pointed out in the [markdown guidelines](https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-markdown/blob/master/ProjectManagementFormat.md)

**Comment by lussierc** [comment]
Hi all, I will implement the suggested changes and then make a PR for the branch where we can discuss further.

For now, I am closing this issue.
